### ISSUE TITLE
Sorting not working?

### ISSUE THREAD

**Issue by ledowong** [izenn/padopt#12]
Hi,

I recently rewrite padopt (https://github.com/ledowong/padopt) with image analysis feature and responsive UI. Now I am working on profile, and found out that sorting is not working as expected.

Tested on your fork as well.
Board (import): pybgbgbpyryprgpghphhyphrhghgbb
Kirin profile, max path length 30, Computation length 400.

### Sorting W > L or W > ↯
Solution #8 is the only one has M=25.

### Sorting M > ↯ > W or M > W > ↯
No solutions have M=25....
Expected the solution #8 show up at first solution.

Any idea?

Thanks,
Leonardo

**Comment by izenn** [comment]
I'm going to leave multiplier in but figure out the sorting issue -- i've seen a similar issue, but i think it is more a problem with the sorting than with the multiplier (my guess is i have a typo)

**Comment by izenn** [comment]
so i found the issue with the multiplier/weight sorter (typo) however, it looks like the first/best result is missing

**Comment by izenn** [comment]
fixed in c697a04

**Comment by ledowong** [comment]
Thanks! I merged this fix into my fork, and add live re-sorting support. (https://github.com/ledowong/padopt/commit/ddb4c363f8c01f7f4ec57032d59516d1f8999588)
